### ISSUE TITLE
[Documentation] Would it be possible to add an example how to use tocer from within a simple .md file (in the main README)?

### ISSUE THREAD

**Issue by shevegen** [bkuhlmann/tocer#3]
Hello Brooke,

I just noticed your tocer-gem on rubygems.org.

I use markdown for my gems and admittedly, I use a very simple markdown.

Other than headers and bold text, and an image here or there, I think that sums up
most of my markdown-use so far in the last ... two years or so. :-)

Anyway, to my suggestion:

- Would it be possible to add a few more, simple examples to tocer, how to use
it from any existing .md file? E. g. anything that would easily allow me (or other
people) to jump-start with tocer. Right now I can see the documentation to tocer
and it's good, -> http://www.rubydoc.info/gems/tocer/7.1.0#command-line-interface-cli

But I am not entirely sure how to use tocer from an existing .md file.

If you could add a minimum example for the next tocer release, that would be
great! Feel free to close this issue at any moment in time.

Thanks!

**Comment by bkuhlmann** [comment]
Hey Robert, thanks for the feedback. Glad you like the gem!

This is in the documentation but, under the covers, Tocer uses the [Runcom](https://github.com/bkuhlmann/runcom) to power its customization. Based on your comments above, I just added the following [documentation](https://github.com/bkuhlmann/runcom#examples) to the Runcom gem. For me, at least, it's a lot easier to write this once in a single location rather than maintain the same documentation across all of my projects since I use the Runcom gem in a lot of my projects (Tocer included).

If it helps, for me personally, I don't actually use the global configuration for Tocer (i.e. `~/.config/tocer/configuration.yml`) I actually define a custom configuration per project. For example, the production app at my company has the following documentation structure:

```
  ./README.md
  ./doc/api.md
  ./doc/services/instagram.md
  ./doc/services/intercom.md
  ./doc/services/twilio.md
  ./doc/services/stripe.md
  ./doc/services/shopify.md
  ./doc/services/aws.md
```

I then have the following configuration file defined within the project:

`./config/tocer/configuration.yml`

...which then has the following contents:

```
:includes:
  - README.md
  - doc/api.md
  - doc/services/**/*
```

Tocer knows how to pick up the custom configuration due to the combination of `direnv` and `Runcom`. This allows me to type `tocer -g` to update the Table of Contents for all of those files with a single command.

Is that helpful?

**Comment by bkuhlmann** [comment]
:information_source: I've also added this [commit](https://github.com/bkuhlmann/tocer/commit/fd23593a703d80f4d0cf2b3d7ecadccc10e2b76a) which points to the Runcom examples too.

**Comment by bkuhlmann** [comment]
ℹ️ Closing this issue due to no further feedback.
